import re

FILE_PATH = "ERRORS_SOURCE_ONLY.md"

import sys
sys.stdout.reconfigure(encoding='utf-8')

def main():
    with open(FILE_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    # Regex to match each error block
    # Example:
    # ### ERR-001 [🔴 CRITICAL] Leftover debugger statement
    # - **File**: pedantic_audit.py
    # - **Line**: 31
    # - **Category**: Dead code and unreachable blocks
    
    block_regex = re.compile(r'### (ERR-\d{3}) \[(🔴 CRITICAL|🟡 WARNING|🔵 INFO)\] (.*?)\n- \*\*File\*\*: (.*?)\n- \*\*Line\*\*: (\d+)', re.DOTALL)
    
    errors = []
    for match in block_regex.finditer(content):
        err_id = match.group(1)
        severity_raw = match.group(2)
        title = match.group(3)
        file_path = match.group(4)
        line_num = int(match.group(5))
        
        # Severity score for sorting: CRITICAL=1, WARNING=2, INFO=3
        sev_score = 1 if "CRITICAL" in severity_raw else (2 if "WARNING" in severity_raw else 3)
        
        errors.append({
            'id': err_id,
            'severity': severity_raw,
            'title': title,
            'file': file_path,
            'line': line_num,
            'sev_score': sev_score
        })

    # Phase 1: Build dependency graph
    # Since all errors were generated by isolated regex heuristics (not AST/compiler downstream errors), 
    # there are NO logical prerequisites between them. They are all structurally independent.
    # We will log them all as independent.
    
    # Phase 2: Topological Sort
    # Rule 1: No constraints
    # Rule 2: Sort by severity (🔴 first, then 🟡, then 🔵)
    # Rule 3: Sort by file path alphabetically, then by line number ascending
    errors.sort(key=lambda x: (x['sev_score'], x['file'], x['line']))

    # Print output
    print("Dependency graph:")
    # We won't print 475 independent lines to terminal to avoid spam, just summarize
    print(f"  All {len(errors)} errors are regex-isolated heuristics and structurally independent.")
    print("⚠️ Cycles detected: none\n")

    print(f"Ordered fix queue ({len(errors)} errors):")
    queue_lines = []
    for idx, e in enumerate(errors):
        # Format: [ 1] ERR-003 🔴  path/to/file.ts:14   — Broken import of AuthService
        icon = "🔴" if e['sev_score'] == 1 else ("🟡" if e['sev_score'] == 2 else "🔵")
        q_str = f"  [{idx+1:3d}] {e['id']} {icon}  {e['file']}:{e['line']} — {e['title']}"
        queue_lines.append(q_str)
    
    # Print first 10 and last 3 to console
    for q in queue_lines[:10]: print(q)
    if len(queue_lines) > 13:
        print("  ...")
        for q in queue_lines[-3:]: print(q)
        
    # Prepend the Queue to ERRORS_SOURCE_ONLY.md
    queue_header = "## Fix Queue (auto-generated — do not edit manually)\n```\n" + "\n".join(queue_lines) + "\n```\n\n"
    
    # Insert right after the title
    new_content = content.replace("# Project Error Audit - SOURCE ONLY\n\n", "# Project Error Audit - SOURCE ONLY\n\n" + queue_header)
    
    with open(FILE_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)
        
    print("\nPhase 1 & 2 complete. Queue written to top of ERRORS_SOURCE_ONLY.md.")

if __name__ == "__main__":
    main()
